[package]
name = "arandu-render-api"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
arandu-model = { path = "../arandu-model" }
arandu-confluence = { path = "../arandu-confluence" }
arandu-geometry = { path = "../arandu-geometry" }

[lints]
workspace = true
